# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 180, 761, 191))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: rgb(0, 0, 0);")
        self.menubar.setObjectName("menubar")
        self.menuSERIES = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.menuSERIES.setFont(font)
        self.menuSERIES.setStyleSheet("color: rgb(0, 0, 0);")
        self.menuSERIES.setObjectName("menuSERIES")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.submenu_Registrar_Serie = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.submenu_Registrar_Serie.setFont(font)
        self.submenu_Registrar_Serie.setObjectName("submenu_Registrar_Serie")
        self.submenu_Listar_Series = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.submenu_Listar_Series.setFont(font)
        self.submenu_Listar_Series.setObjectName("submenu_Listar_Series")
        self.submenu_List_Widget = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.submenu_List_Widget.setFont(font)
        self.submenu_List_Widget.setObjectName("submenu_List_Widget")
        self.submenu_Table_Widget = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        self.submenu_Table_Widget.setFont(font)
        self.submenu_Table_Widget.setObjectName("submenu_Table_Widget")
        self.menuSERIES.addAction(self.submenu_Registrar_Serie)
        self.menuSERIES.addAction(self.submenu_Listar_Series)
        self.menuSERIES.addAction(self.submenu_List_Widget)
        self.menuSERIES.addAction(self.submenu_Table_Widget)
        self.menubar.addAction(self.menuSERIES.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplicación para gestionar series"))
        self.label.setText(_translate("MainWindow", "Mis Series"))
        self.menuSERIES.setTitle(_translate("MainWindow", "SERIES"))
        self.submenu_Registrar_Serie.setText(_translate("MainWindow", "Registrar Serie"))
        self.submenu_Listar_Series.setText(_translate("MainWindow", "Listar Series"))
        self.submenu_List_Widget.setText(_translate("MainWindow", "List Widget"))
        self.submenu_Table_Widget.setText(_translate("MainWindow", "Table Widget"))
