# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_modificar_series.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_guardar_cambios = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar_cambios.setGeometry(QtCore.QRect(40, 400, 591, 81))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(18)
        self.btn_guardar_cambios.setFont(font)
        self.btn_guardar_cambios.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(99, 99, 99);")
        self.btn_guardar_cambios.setObjectName("btn_guardar_cambios")
        self.entrada_lanzamiento = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_lanzamiento.setGeometry(QtCore.QRect(270, 290, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.entrada_lanzamiento.setFont(font)
        self.entrada_lanzamiento.setObjectName("entrada_lanzamiento")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 340, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.entrada_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_titulo.setGeometry(QtCore.QRect(270, 140, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.entrada_titulo.setFont(font)
        self.entrada_titulo.setObjectName("entrada_titulo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 140, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.entrada_vista = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_vista.setGeometry(QtCore.QRect(270, 340, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.entrada_vista.setFont(font)
        self.entrada_vista.setObjectName("entrada_vista")
        self.entrada_temporadas = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_temporadas.setGeometry(QtCore.QRect(270, 240, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.entrada_temporadas.setFont(font)
        self.entrada_temporadas.setObjectName("entrada_temporadas")
        self.entrada_sinopsis = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_sinopsis.setGeometry(QtCore.QRect(270, 190, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.entrada_sinopsis.setFont(font)
        self.entrada_sinopsis.setObjectName("entrada_sinopsis")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 591, 81))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 290, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Yataghan")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro de Series"))
        self.btn_guardar_cambios.setText(_translate("MainWindow", "GUARDAR CAMBIOS"))
        self.label_5.setText(_translate("MainWindow", "¿Has visto esta serie? SI o NO"))
        self.label.setText(_translate("MainWindow", "Titulo:"))
        self.label_2.setText(_translate("MainWindow", "Sinopsis:"))
        self.label_6.setText(_translate("MainWindow", "REALIZAR CAMBIOS:"))
        self.label_3.setText(_translate("MainWindow", "Temporadas:"))
        self.label_4.setText(_translate("MainWindow", "Año de lanzamiento:"))
